version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-innodb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: users-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-storage-engine=InnoDB --innodb_flush_log_at_trx_commit=2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: